### ISSUE TITLE
post on database clients

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#161]
* elastic
* solr
* rerddap
* ckanr
* etseed
* sofa
* rrlite

**Comment by sckott** [comment]
Wait until `rrlite` is in ropensci - maybe move sofa over too?

**Comment by sckott** [comment]
@richfitz @jeroenooms @ropensci/owners  Have a draft ready for the databases clients post, see 

https://github.com/ropensci/roweb/blob/master/_drafts/2015-05-15-database-interfaces.md

thoughts?

**Comment by emhart** [comment]
@sckott https://github.com/datacarpentry/R-ecology/blob/gh-pages/06-r-and-sql.Rmd if you are interested in SQL and R (based on `RSQLite`)

**Comment by cboettig** [comment]
Looks great, nice work.

I think some more concrete examples would help motivate the use cases.  I thought Hadley summarized the use cases for the SQL-based databases rather well on the comm call: (1) your data doesn't fit into memory (2) someone gives you data in an SQL format.  

I think these both apply to the NoSQL databases as well, but also I think the NoSQL use cases get more interesting because it's less obvious (at least to me) what the appropriate in-memory analogs are.  For SQL-like databases, when data fits in memory we can make all the same queries much faster using data.frames and with a reasonably nicer syntax using `dplyr` (luckily we can use the same syntax for supported SQL backends too).  

If a set of data.frames is essentially the R analog to an SQL database, what's the NoSQL R-object analog? A list?  What are the native / packaged R tools for working with such structures?  

A key question in mind is whether you see these NoSQL databases as primarily a new shiny drop-in replacement for all the things we used SQL databases for, or whether it is primarily to do manage data that SQL databases were never good at (e.g. heterogeneous, constantly changing schema)?  (I realize the answer probably differs for the different examples here, but teasing that out would help).

I doubt most R users really care about details like [ACID](http://en.wikipedia.org/wiki/ACID) & [BASE](http://en.wikipedia.org/wiki/Eventual_consistency), but maybe there's something there that would be relevant to users selecting an SQL or NoSQL database backend.  

I find myself increasingly interacting with databases (fishbase, ram legacy, gpdd) that use some SQL format as if it were an NoSQL database (e.g. constantly adding things / changing a schema that was never thought through in the first place) when really the whole database would be better off as a few big tables (e.g. .csv files) that easily fit into memory (a few GBs). I often wonder if these would have been better off had they been built with NoSQL, or worse off?

**Comment by sckott** [comment]
thanks @emhart may add list of SQL resources

**Comment by sckott** [comment]
@cboettig 

* more concrete egs: good idea, though since there's so many pkgs to discuss, trying to keep each eg short, but maybe I can do one longer eg
* data.frame equivalent question: definitely data.frame's/matrices map directly into SQL DB's - whereas other R objects don't. Whereas, any R object can map to a NoSQL DB. For data.frame's we've been assuming each row is a "document", since with row based storage it's easy to stream as much data is requested. 
* What's the utility:  A number of use cases: 
    * User already has data in a NoSQL DB
    * Easily get richer query interface than a SQL DB (e.g., with Elasticsearch) 
    * The key-value stores can be a drop in replacement for SQL storage - e.g., @richfitz rrlite is super fast at serializing a data.frame into the serverless Redis thing. __OR__ they can be used for caching purposes, replacing any caching thing currently used in R
* ACID/BASE - I'll see if that makes sense to include
* fishbase/gpdd comment: I don't think I know enough to write about this tradeoff/decision process in the post - anyone else want to add that?

**Comment by richfitz** [comment]
* I also agree that concrete examples would be a good idea.  I wonder though if splitting this into two posts would be a good idea.  One would be: "how databases can improve an R workflow" and the other could be closer to this one "ropensci tools for working with databases".
* I think that there are far more use cases for nosql data than to sql databases; sql databases (IMO) do one thing and do it well -- table handling -- but it's something that R is OK at doing (great compared with non-data-oriented languages).  
  * While the nodbi package focusses on handling tabular data, that feels like a corner case for nosql databases.  The motivating reason for storing tabular data in a nosql database would then become that the *rest* of the pipeline is in a nosql database.
  * Concurrency is going to be another major selling point.  "Setting up" most of the nosql things is trivial (download, run a thing) so getting to a point where you can have multiple R processes doing simultaneous read/write is easy.  Not sure how generally useful that will be but I have a ton of need for that :)
  * Data types (related to * If a set of data.frames is essentially the R analog to an SQL database, what's the NoSQL R-object analog? A list? What are the native / packaged R tools for working with such structures?*) - this is where Redis shines.  I need to do a decent demo of RedisAPI soon; having a bunch of decent data types to play with is super fun.
  * The free form thing really shines in places like [indexable serialised objects](http://htmlpreview.github.io/?https://raw.githubusercontent.com/richfitz/storr/master/inst/doc/storr.html#lists-and-indexable-serialisation) which is something that turned up as a [hackathon issue](https://github.com/ropensci/unconf/issues/37) but was never progressed.  The more I play around with this stuff, the smaller the parallels with SQL database gets.
* ACID/BASE - not sure about that, but I do know about [acid house](https://soundcloud.com/ninja-tune/solid-steel-radio-show-31-5) :notes:

**Comment by sckott** [comment]
> I wonder though if splitting this into two posts would be a good idea. One would be:  _how databases can improve an R workflow_ and the other could be closer to this one _ropensci tools for working with databases_

Any votes on this? 1 vs. 2 posts?

**Comment by cboettig** [comment]
Seems like it might be weird to do (1) w/o mentioning 2.  Would it make
sense to do a subset of the packages per post (e.g. key-value store only)?

**Comment by sckott** [comment]
@cboettig i agree that would be weird. 

I vote for keeping the 1 blog post - and expanding more on use cases and motivation for why people should care about (especially nosql) DB's in R

**Comment by cboettig** [comment]
sounds good to me.

**Comment by karthik** [comment]
I also vote for a single post, but more clarity in the introduction and use
cases.

**Comment by sckott** [comment]
after reading more on acid and base stuff, I think most of our audience wouldn't need to worry about that kind of stuff

**Comment by sckott** [comment]
@richfitz I think you said something about the rrlite eg. Is it okay? hoping to get this up soon - let me know

**Comment by sckott** [comment]
@ropensci/owners new version https://github.com/ropensci/roweb/blob/master/_drafts/2015-05-15-database-interfaces.md 

i think i'll post tomorrow morning - unless there's any more feedback  ????

**Comment by karthik** [comment]
Looks great Scott! :+1: 
![](http://media2.giphy.com/media/3Cpj1wgUwH5Kw/200.gif)

**Comment by jennybc** [comment]
I would read all sorts of issue threads just for @karthik's gifs.

**Comment by karthik** [comment]
@jennybc Not sure if that's a compliment or a judgement.

![](http://i.imgur.com/NP1yqD4.gif)

**Comment by jennybc** [comment]
compliment! for sure

**Comment by karthik** [comment]
![](http://media0.giphy.com/media/KR9OgQyWAwIIE/200.gif)

![](http://media1.giphy.com/media/1guRIRFV5gN4ikrUakg/200.gif)

**Comment by sckott** [comment]
heh, well here's my offering 

![](http://media.tumblr.com/5ff8c5ced7c3626c254dae01147069e6/tumblr_inline_mnoqamZpgV1qz4rgp.gif)

**Comment by jennybc** [comment]
Will rOpenSci be my official Gif provider for useR?

**Comment by karthik** [comment]
![](http://bukk.it/yesh.gif)
