### ISSUE TITLE
blog post on map/spatial graphics?

### ISSUE THREAD

**Issue by cboettig** [ropensci/roweb#166]
Our tutorials include quite a number of different examples that involve map/spatial graphics output.  I was wondering if it might provide a useful blog-post to summarize some of the alternatives (including javascript-based and non-javascript-based options) and their main use-cases / strengths and weaknesses.  

e.g. 

- What seems to be the best for static/publication plots? For interactive plots?
- Are there key features missing from any particular format?
- is a certain format best for layering certain kinds of data? 
- Which rely on standard underlying data formats (like geojson) and which on custom formats? 

maybe I'm overstating the diversity of options here, but I for one could use a little overview.  Thoughts?

**Comment by sckott** [comment]
good idea @cboettig maybe combine with #160

**Comment by sckott** [comment]
also talk about the few projects we have in this space:

* geojsonio
* wellknown
* spocc?
* gistr (ish? to share maps)
* (future) turf.js at hackathon

**Comment by sckott** [comment]
@cboettig I definitely can't claim to be an expert on these various different mapping pkgs, but we could get feedback from folks that are smarter at this stuff, and caveat w/ this is just our opinion

**Comment by sckott** [comment]
i think one point that can be made is about trying to make the spatial stack less burdensome - the GDAL dependency chain is a real pain, and some in the R spatial comm. think we need new tools

**Comment by karthik** [comment]
Sounds like a good idea. Morgan hasn't rsvp'ed yet so we may/may not hit turf at the unconf (although we could do it after; not that we're struggling for projects).

@sckott Good idea (re your last comment). It's good for us to establish and identify new directions in these blog posts.

**Comment by cboettig** [comment]
Sounds great; maybe more than a one-part blog-post here though.  I think
the low-hanging fruit is simply to have a single post that mentions each of
the different tools explicitly for visualizing spatial data, with only a
very minimal overview of what they are.  The CRAN spatial taskview doesn't
even have a section for visualization describing the tools already
metnioned here.  Getting some opinions out there could spark discussion,
and encourage people in the comments section to weigh in.

Really like the direction about stack dependencies too.  Certainly the
docker stuff is one avenue to address this, but has tradeoffs like anything
else.

**Comment by sckott** [comment]
@cboettig right about spatial taskview, but we are trying to help fill that void with https://github.com/ropensci/maptools maintained by @jhollist

**Comment by jhollist** [comment]
I am making slow but steady progress on the taskview.  Was able to spend some time on Friday.  I think if I get a good chunk of time (day or so), I could have a draft ready soon.

That being said, as @sckott noted this is more to fill to void in the spatial task view than address the questions you raise at the top of this issue, @cboettig.  Those are some good ones.

The javascript solutions are very cool but a couple of problems I have with them are:

1. Projections are kind of abstracted away.  Data are assumed to be wgs84, long, lat.  For mapping only this is probably fine, but what happens when you start to look at length, area, etc.  A projection is occurring but not always clear what it is.  For instance, after @sckott  posted the issue about turf.js (I hadn't heard of it, but it looks really cool!) I looked at it a bit.  The area results are returned in square meters so a transformation is happening at some point, but the users doesn't get to specify how that is done.  
2. Raster data don't seem to be well supported for mapping or analysis.  I work with raster data quite a bit (e.g. elevation) and it isn't clear to me how you would visualize that in something leaflet.  

In any event, I think a blog post along these lines would be very useful.  Perhaps if I had the taskview ready to go to CRAN the post and task view could go out about the same time

**Comment by sckott** [comment]
@jhollist nice work on the taskview :)

good point about projections. In one of the issues in the turf.js repo, they mention [proj4js](https://github.com/proj4js/proj4js), which could be used if we want to do a pure javascript thing - i think d3.js has projection utilities as well. 

I'll get a draft blog post sketch up soon with ideas and we can go from there.

**Comment by cboettig** [comment]
@jhollist Wow, the taskview looks great so far! Guess I've been hiding under a rock.  Yup, just like you say, seems like there's still lots of scope to understand the trade-offs and strengths / limitations etc.  

Not sure if it is more in-scope for the task-view or the blog post, but in getting a handle on the different packages it would be useful to know what format each package expects spatial data to be in, (and maybe where pipelines exist to move from one to the other).

**Comment by karthik** [comment]
> Perhaps if I had the taskview ready to go to CRAN the post and task view could go out about the same time

That would be great. But no rush, we can just mention it in the post regardless.

**Comment by jhollist** [comment]
I can't take all the credit for what is in there.  @karthik and @sckott (plus many others) passed off a pretty good start.

@sckott  I am very interested to see what comes out of these post(s).  I feel like the spatial stuff has been a bit stagnant for  a while (since ASDAR).  `rgeos` has been a great addition for me, and I find `rgdal` indispensable.  The basic vis is there with the sp plotting functions and I have added some rudimentary interactive tools for sp and raster objects with [quickmapr](https://github.com/jhollist/quickmapr).  That being said it is a bit heavy with all the required libraries and the viz is at best ho-hum.  The javascript libraries provide a modern face to a lot of these tools, but some questions still exist (at least for me) on what is happening behind the scene.  Anyway feels like things have picked up speed in the spatial analysis front in the last year and a review of these is certainly in order.

@cboettig That is a fantastic idea.  It may be in scope for the task view.   At a minimum I could include supported input formats in the annotation on each package.  That would be easy enough and makes a lot of sense. Also there is currently an I/O section and a discusison of the pipelines could work there.

**Comment by cboettig** [comment]
Just a note that this week's Nature has a toolbox on some geospatial vis tools, http://www.nature.com/news/data-visualization-science-on-the-map-1.17024?WT.ec_id=NATURE-20150305

**Comment by sckott** [comment]
I'm rebooting this, trying to finish something up on this topic. New draft in, still to flesh out brief discussion of each and examples. 

I will now only cover ropensci software. I don't think I'm equipped to post on the R ecosystem for mapping, will try to finish soon
