### ISSUE TITLE
Move deployment to Travis

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb#179]
Given the recent troubles building the sites locally we should consider moving to automatic deployment via Travis. We can encrypt some ssh keys to facilitate the rsync.

**Comment by cboettig** [comment]
Are you sure you can encrypt ssh keys on travis? My recollection is that
the maximum string length for encryption is pretty short. (I don't think
this is a problem if we just use circle-ci or drone instead)

Are we using dynamic features that need to be deployed on ASO? If so would
it make sense to deploy those separately and host directly on github? (i.e.
then we could deploy to github with a PAT instead of an ssh key...)
