### ISSUE TITLE
Post on software review

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#221]

**Comment by karthik** [comment]
I will do a review if someone else can also read through.

**Comment by sckott** [comment]
> I will do a review

you mean write? or write a draft?  let me know if too busy and I can start

**Comment by karthik** [comment]
Sorry, I thought there was a draft already. Yes, you should start but I'll contribute (esp since I have more context to add from some recent discussions).

**Comment by sckott** [comment]
started the post, have at it @noamross and @karthik

**Comment by richfitz** [comment]
I just took a quick glance at the post; I think it focusses too much on the technical side of things.  I think one of the things that has made the onboarding process good so far are the social side of things - it's non adversarial, it's focussed on improving packages first (and moving into the suite second) and it's explicitly conversational with a back and forth rather than a journal-style "review, revise and cross fingers hoping you hit the important points".

What's less clear is if this utopian model will scale.

**Comment by noamross** [comment]
Will get to writing this evening probably, but I agree with Rich  on themes:

-  How this is similar and different from journal reviews, and why
- Benefits and snafus of the system: reviewers can interact and contribute
via PRs; limited reviewer pool so far
-  Scaling is an open question. Upcoming changes, e.g. journal-like
assigned editor roles to extend the reviewer network, will attempt to
address this.

**Comment by noamross** [comment]
Re-wrote the post in PR #223.  @richfitz, do you think I covered what you described?

**Comment by sckott** [comment]
closing, posting monday morning
