### ISSUE TITLE
geospatial post 

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb#270]
@stefaniebutland when you get a chance, have a look at the draft https://github.com/ropensci/roweb/blob/master/_drafts/2016-11-16-geospatial-suite.Rmd 

It's in .Rmd format, cause I think we should have a few code examples, but let me know if you think it'd be better to avoid code egs for this post

there's many placeholder ulrs, words, etc. to fill in still

**Comment by stefaniebutland** [comment]
@sckott I def think it’s good to have this post in Rmd to include code.

Hope these comments are helpful.
Consider the first para as the only para that some people might read so tell them why rOpenSci’s contribution to research involving geospatial stuff is awesome. Some of these 1-para readers might be potential funders, or partner orgs who land on our blog from NumFOCUS newsletter and this plants seed of “hey, I think rOpenSci was working on that... you should give them a meeelleeon dollars”

Intro should have 1-2 lines on what geospatial is in lay terms. Then what are specific applications of geospatial that the rOpenSci community or partner organizations would recognize as having value. Can you give an example of someone in our community who uses components of our geospatial suite and what they’ve used it for? An example of published research using components of the geospatial suite (i.e. subtly show readers that they should cite our stuff and will be recognized for doing so)? This first para or two should be explanatory and put things in context.

How does this relate to March 2016 post [“rOpenSci geospatial libraries”](https://ropensci.org/blog/blog/2016/03/17/ropensci-geospatial-stack)?
You could refer back to this post to indicate in plain terms what has been added since then. 

At start, explain WKT and GeoJSON in words, then ok to link to spec & wikipedia. I found the taskviews for maptools and spatial helpful to understand a bit of what geospatial is about.

In this section “There are many geospatial tools in R already -”, make it clear what rOpenSci’s contributions are. e.g. what need was not met without rOpenSci geospatial suite. 

Given the title, The rOpenSci Geospatial Suite, explicitly state what tools make up the suite (maybe that's the table you have already so just give clear heading or explanation). Where needed, state how they work with other R tools for research involving geospatial stuff. 

Just before end, say what gaps still exist (what can’t someone do yet) and what we plan to develop to address this.

Move this to the end “Let us know if you have any feedback on these packages, and/or if you think there's anything else we should be thinking about making in this space.” Maybe also ask people to tell you how they’re using these tools and then ask that feedback question.

**Comment by sckott** [comment]
Good thinking on the first two paragraphs, will shape those up.

> How does this relate to March 2016 post “rOpenSci geospatial libraries”?

good idea, will refer back to that

> At start, explain WKT and GeoJSON in words, then ok to link to spec & wikipedia. I found the taskviews for maptools and spatial helpful to understand a bit of what geospatial is about.

okay

> In this section “There are many geospatial tools in R already -”, make it clear what rOpenSci’s contributions are. e.g. what need was not met without rOpenSci geospatial suite.

yeah, some more text on that is a good idea

> Given the title, The rOpenSci Geospatial Suite, explicitly state what tools make up the suite (maybe that's the table you have already so just give clear heading or explanation). 

this section covers what is included https://github.com/ropensci/roweb/blob/master/_drafts/2016-11-16-geospatial-suite.Rmd#the-tools

> Where needed, state how they work with other R tools for research involving geospatial stuff.

can highlight integrations more

> Just before end, say what gaps still exist (what can’t someone do yet) and what we plan to develop to address this.

yeah, good pt

> Move this to the end “Let us ..

sounds good

**Comment by stefaniebutland** [comment]
Looking good!

"wether it be history," > whether
I'd omit "gov't and non-profit since they're not disciplines. You could add "public health" e.g epidemiology

suggestion:
"We covered the state of our geospatial tools in March of this year bit a lot has changed since then so we thought it would be useful for us and readers to do an overview of these tools and future work."

 shapefile's - no apostrophe

don't repeat "use cases" so many times in opening of rOpensci use cases section

rOpenSci has an increasing suite ... say "growing" suite
